[package]
name = "erebus-cli"
version = "0.5.0"
edition = "2021"
description = "erebus CLI — package any app into a single self-extracting binary"

[[bin]]
name = "erebus"
path = "src/main.rs"

[dependencies]
erebus-core = { path = "../erebus-core" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
sha2 = "0.10"
ed25519-dalek = { version = "2", default-features = false, features = ["alloc", "std", "rand_core", "zeroize"] }
zeroize = "1"
rand = "0.8"
tempfile = "3"
walkdir = "2"
which = "7"
hex = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls", "multipart"] }
anyhow = "1"
human-panic = "2"
clap_complete = "4"
clap_mangen = "0.2"
tar = "0.4"
xz2 = "0.1"
zip = "2"
flate2 = "1"
libc = "0.2"
crossterm = "0.28"
ratatui = "0.29"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
doc_markdown = "warn"
unwrap_used = "allow"
expect_used = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_precision_loss = "allow"
items_after_statements = "allow"
format_push_string = "allow"
uninlined_format_args = "allow"
if_not_else = "allow"
manual_let_else = "allow"
io_other_error = "allow"
map_unwrap_or = "allow"
unnecessary_wraps = "allow"
single_match_else = "allow"
similar_names = "allow"
too_many_lines = "allow"
struct_excessive_bools = "allow"
needless_borrows_for_generic_args = "allow"
redundant_closure_for_method_calls = "allow"
unused_async = "allow"
trivially_copy_pass_by_ref = "allow"
module_inception = "allow"
return_self_not_must_use = "allow"
must_use_unit = "allow"
redundant_else = "allow"
option_if_let_else = "allow"
needless_pass_by_value = "allow"
unnecessary_map_or = "allow"
enum_variant_names = "allow"
unnecessary_cast = "allow"
redundant_clone = "allow"
ref_option = "allow"
cmp_owned = "allow"