"""Dependency lockfile: read/write ``xbin.lock``.

The lockfile records what Features A/B/C detected and fetched, so
subsequent builds skip detection entirely and work offline.  Staleness
is tracked by hashing the Dockerfile — if it changes, the lock is stale
and detection re-runs automatically.

Schema::

    [detect]
    dockerfile_sha256 = "..."
    detected_at = "..."

    [[dep]]
    kind = "pip"
    name = "flask"
    version = "2.0"
"""

from __future__ import annotations

import hashlib
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore[no-redef]

from .dockerfile import DetectedDep
from .fetch import FetchResult

LOCKFILE_NAME = "xbin.lock"


# ---------------------------------------------------------------------------
# Read
# ---------------------------------------------------------------------------


def read_lock(app_dir: Path) -> dict | None:
    """Read ``xbin.lock`` from *app_dir*. Returns None if missing or invalid."""
    path = app_dir / LOCKFILE_NAME
    if not path.is_file():
        return None
    try:
        with open(path, "rb") as f:
            return tomllib.load(f)
    except (OSError, tomllib.TOMLDecodeError):
        return None


def lock_deps(lock: dict) -> list[DetectedDep]:
    """Extract ``[[dep]]`` entries from a parsed lock dict as DetectedDep instances."""
    deps: list[DetectedDep] = []
    for entry in lock.get("dep", []):
        deps.append(
            DetectedDep(
                kind=entry["kind"],
                name=entry["name"],
                version=entry.get("version"),
                url=entry.get("url"),
                source="xbin.lock",
                confidence="high",
            )
        )
    return deps


# ---------------------------------------------------------------------------
# Staleness
# ---------------------------------------------------------------------------


def hash_dockerfile(app_dir: Path) -> str:
    """SHA-256 hex digest of the Dockerfile, or empty string if none exists."""
    dockerfile = app_dir / "Dockerfile"
    if not dockerfile.is_file():
        return ""
    h = hashlib.sha256()
    try:
        with open(dockerfile, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
    except OSError:
        return ""
    return h.hexdigest()


def is_lock_fresh(app_dir: Path, lock: dict) -> bool:
    """Check if the lock's Dockerfile hash matches the current Dockerfile."""
    detect = lock.get("detect", {})
    stored_hash = detect.get("dockerfile_sha256", "")
    current_hash = hash_dockerfile(app_dir)
    return stored_hash == current_hash


# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------


def write_lock(
    app_dir: Path,
    deps: list[DetectedDep],
    results: list[FetchResult] | None = None,
) -> Path:
    """Write ``xbin.lock`` to *app_dir*.

    If *results* is provided, fetch SHA-256 hashes are included for
    deps that were successfully fetched.

    Returns the path to the written lockfile.
    """
    # Build a lookup from dep → sha256 for fetched deps.
    sha_by_key: dict[str, str] = {}
    if results:
        for r in results:
            if r.ok and r.sha256:
                key = f"{r.dep.kind}:{r.dep.name}:{r.dep.version}"
                sha_by_key[key] = r.sha256

    lines: list[str] = []
    lines.append("# xbin.lock — auto-generated by `xbin build`. Do not edit by hand.")
    lines.append("# Re-run with `xbin build --redetect` to regenerate.")
    lines.append("")

    # [detect] section
    lines.append("[detect]")
    lines.append(f'dockerfile_sha256 = "{hash_dockerfile(app_dir)}"')
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines.append(f'detected_at = "{now}"')
    lines.append("")

    # [[dep]] entries
    for dep in deps:
        lines.append("[[dep]]")
        lines.append(f'kind = "{dep.kind}"')
        lines.append(f'name = "{dep.name}"')
        if dep.version:
            lines.append(f'version = "{dep.version}"')
        if dep.url:
            lines.append(f'url = "{dep.url}"')
        key = f"{dep.kind}:{dep.name}:{dep.version}"
        if key in sha_by_key:
            lines.append(f'sha256 = "{sha_by_key[key]}"')
        lines.append("")

    lock_path = app_dir / LOCKFILE_NAME
    lock_path.write_text("\n".join(lines))
    return lock_path


# ---------------------------------------------------------------------------
# Orchestration: detect → fetch → lock (or read lock)
# ---------------------------------------------------------------------------


def detect_or_read_lock(
    app_dir: Path,
    *,
    redetect: bool = False,
    verbose: bool = True,
) -> list[DetectedDep] | None:
    """Return locked deps if the lock is fresh, else None (caller should detect).

    If *redetect* is True, always returns None (forces re-detection).
    """
    if redetect:
        if verbose:
            print("[xbin] --redetect: forcing re-detection", file=sys.stderr)
        return None

    lock = read_lock(app_dir)
    if lock is None:
        return None

    if not is_lock_fresh(app_dir, lock):
        if verbose:
            print(
                "[xbin] xbin.lock stale (Dockerfile changed), re-detecting",
                file=sys.stderr,
            )
        return None

    deps = lock_deps(lock)
    if verbose:
        detected_at = lock.get("detect", {}).get("detected_at", "?")
        print(
            f"[xbin] xbin.lock fresh ({len(deps)} deps, detected {detected_at})",
            file=sys.stderr,
        )
    return deps


def write_lock_from_results(
    app_dir: Path,
    deps: list[DetectedDep],
    results: list[FetchResult],
    verbose: bool = True,
) -> Path:
    """Write xbin.lock after a detection + fetch cycle."""
    lock_path = write_lock(app_dir, deps, results)
    if verbose:
        print(f"[xbin] wrote {lock_path.name} ({len(deps)} deps)", file=sys.stderr)
    return lock_path
